/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Customer extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8959539230510816548L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Customer\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"num_order\",\"type\":\"int\"},{\"name\":\"Age\",\"type\":\"int\"},{\"name\":\"Tel\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Customer> ENCODER =
      new BinaryMessageEncoder<Customer>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Customer> DECODER =
      new BinaryMessageDecoder<Customer>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Customer> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Customer> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Customer>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Customer to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Customer from a ByteBuffer. */
  public static Customer fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int id;
  @Deprecated public int num_order;
  @Deprecated public int Age;
  @Deprecated public java.lang.CharSequence Tel;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Customer() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param num_order The new value for num_order
   * @param Age The new value for Age
   * @param Tel The new value for Tel
   */
  public Customer(java.lang.Integer id, java.lang.Integer num_order, java.lang.Integer Age, java.lang.CharSequence Tel) {
    this.id = id;
    this.num_order = num_order;
    this.Age = Age;
    this.Tel = Tel;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return num_order;
    case 2: return Age;
    case 3: return Tel;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: num_order = (java.lang.Integer)value$; break;
    case 2: Age = (java.lang.Integer)value$; break;
    case 3: Tel = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'num_order' field.
   * @return The value of the 'num_order' field.
   */
  public java.lang.Integer getNumOrder() {
    return num_order;
  }

  /**
   * Sets the value of the 'num_order' field.
   * @param value the value to set.
   */
  public void setNumOrder(java.lang.Integer value) {
    this.num_order = value;
  }

  /**
   * Gets the value of the 'Age' field.
   * @return The value of the 'Age' field.
   */
  public java.lang.Integer getAge() {
    return Age;
  }

  /**
   * Sets the value of the 'Age' field.
   * @param value the value to set.
   */
  public void setAge(java.lang.Integer value) {
    this.Age = value;
  }

  /**
   * Gets the value of the 'Tel' field.
   * @return The value of the 'Tel' field.
   */
  public java.lang.CharSequence getTel() {
    return Tel;
  }

  /**
   * Sets the value of the 'Tel' field.
   * @param value the value to set.
   */
  public void setTel(java.lang.CharSequence value) {
    this.Tel = value;
  }

  /**
   * Creates a new Customer RecordBuilder.
   * @return A new Customer RecordBuilder
   */
  public static Customer.Builder newBuilder() {
    return new Customer.Builder();
  }

  /**
   * Creates a new Customer RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Customer RecordBuilder
   */
  public static Customer.Builder newBuilder(Customer.Builder other) {
    return new Customer.Builder(other);
  }

  /**
   * Creates a new Customer RecordBuilder by copying an existing Customer instance.
   * @param other The existing instance to copy.
   * @return A new Customer RecordBuilder
   */
  public static Customer.Builder newBuilder(Customer other) {
    return new Customer.Builder(other);
  }

  /**
   * RecordBuilder for Customer instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Customer>
    implements org.apache.avro.data.RecordBuilder<Customer> {

    private int id;
    private int num_order;
    private int Age;
    private java.lang.CharSequence Tel;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Customer.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.num_order)) {
        this.num_order = data().deepCopy(fields()[1].schema(), other.num_order);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Age)) {
        this.Age = data().deepCopy(fields()[2].schema(), other.Age);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.Tel)) {
        this.Tel = data().deepCopy(fields()[3].schema(), other.Tel);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Customer instance
     * @param other The existing instance to copy.
     */
    private Builder(Customer other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.num_order)) {
        this.num_order = data().deepCopy(fields()[1].schema(), other.num_order);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Age)) {
        this.Age = data().deepCopy(fields()[2].schema(), other.Age);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.Tel)) {
        this.Tel = data().deepCopy(fields()[3].schema(), other.Tel);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Integer getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public Customer.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public Customer.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'num_order' field.
      * @return The value.
      */
    public java.lang.Integer getNumOrder() {
      return num_order;
    }

    /**
      * Sets the value of the 'num_order' field.
      * @param value The value of 'num_order'.
      * @return This builder.
      */
    public Customer.Builder setNumOrder(int value) {
      validate(fields()[1], value);
      this.num_order = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'num_order' field has been set.
      * @return True if the 'num_order' field has been set, false otherwise.
      */
    public boolean hasNumOrder() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'num_order' field.
      * @return This builder.
      */
    public Customer.Builder clearNumOrder() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'Age' field.
      * @return The value.
      */
    public java.lang.Integer getAge() {
      return Age;
    }

    /**
      * Sets the value of the 'Age' field.
      * @param value The value of 'Age'.
      * @return This builder.
      */
    public Customer.Builder setAge(int value) {
      validate(fields()[2], value);
      this.Age = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'Age' field has been set.
      * @return True if the 'Age' field has been set, false otherwise.
      */
    public boolean hasAge() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'Age' field.
      * @return This builder.
      */
    public Customer.Builder clearAge() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'Tel' field.
      * @return The value.
      */
    public java.lang.CharSequence getTel() {
      return Tel;
    }

    /**
      * Sets the value of the 'Tel' field.
      * @param value The value of 'Tel'.
      * @return This builder.
      */
    public Customer.Builder setTel(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.Tel = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'Tel' field has been set.
      * @return True if the 'Tel' field has been set, false otherwise.
      */
    public boolean hasTel() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'Tel' field.
      * @return This builder.
      */
    public Customer.Builder clearTel() {
      Tel = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Customer build() {
      try {
        Customer record = new Customer();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.num_order = fieldSetFlags()[1] ? this.num_order : (java.lang.Integer) defaultValue(fields()[1]);
        record.Age = fieldSetFlags()[2] ? this.Age : (java.lang.Integer) defaultValue(fields()[2]);
        record.Tel = fieldSetFlags()[3] ? this.Tel : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Customer>
    WRITER$ = (org.apache.avro.io.DatumWriter<Customer>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Customer>
    READER$ = (org.apache.avro.io.DatumReader<Customer>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
